package org.example.steamgameservice.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.util.List;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "games")     // MongoDB collection name
public class Game {
    @Id
    private String id;      // Unique ID generated by MongoDB

    private String title;

    private String description;

    private BigDecimal price;

    private List<String> genres;

    private String developer;

    private String publisher;

    private int releaseYear;

    public List<Review> reviews;
}
